### ISSUE TITLE
ERROR: Received an exception while trying to start Appium session: org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Original error: ondemand.saucelabs.com

### ISSUE THREAD

**Issue by mrk-han** [appium/java-client#1306]
## Description

This may be a shot in the dark, but we are seeing a weird error after migrating to a linux build agent behind a VPN. We have double checked the ports + ips are whitelisted but thought I would post this stacktrace originating in the Java-Client to see if you have any ideas.

`ERROR: Received an exception while trying to start Appium session: org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Original error: ondemand.saucelabs.com`

I just want to figure out if this might be stemming from a java-client / linux issue? Everything was working fine and still runs fine if we are not on SauceConnect, and not on Linux.

Does this stack trace mean anything to you? Thank you!

## Environment

* Java client build version or git revision if you use some snapshot: 7.3.0
* Appium server version or git revision if you use some snapshot: 1.16.0
* Mobile platform/version under test: Agnostic, but attemping to use Emulator on 10.0
* Real device or emulator/simulator: Em/sim

## Details

We are using a wrapper library called Conductor-Mobile, and launching tests from Jenkins behind an enterprise VPN with a SauceConnect Tunnel. When creating the remote session, I observed a stacktrace with an exception thrown by the Java-Client.

```
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor211.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
```

## Code To Reproduce Issue [ Good To Have ]

```
            steps {
                sauce('SauceOnDemandCreds') {
                    sauceconnect(options: '-p REDACTED:8080 --dns REDACTED -T -vv -l sc.log', sauceConnectPath: '', useGeneratedTunnelIdentifier: true, verboseLogging: true) {
                        run_release_tests(SAUCE_USERNAME, SAUCE_ACCESS_KEY)
                    }
                }
            }
```
^ Jenkins step

```
mvn clean test -Dsurefire.suiteXmlFiles=testng_xmls/saucelabs_by_groupname/priority/saucelabs_handset_mock_regression_priority_1.xml -DconductorCurrentSchemes=sauce-android-mock -DSAUCE_USERNAME=REDACTED -DSAUCE_ACCESS_KEY=REDACTED -DANDROID_APP_FILENAME=Android-Bitrise.apk -DconductorPlatformName=ANDROID '-DANDROID_DEVICE_NAME=Android GoogleAPI Emulator' -DANDROID_PLATFORM_VERSION=10.0
```
^ mvn command run with run_release_tests

`-DconductorCurrentSchemes` points to a yaml array which has desiredCapabilities, this is from the Conductor-Mobile repo https://github.com/willowtreeapps/conductor-mobile/blob/e13b757ee718cb8d09674a225b8eeed4ce097860/src/main/java/com/joss/conductor/mobile/ConductorConfig.java#L147-#L167

We're using it like this:

```
sauce-android-mock:
  noReset: false
  fullReset: true
  hub: https://${SAUCE_USERNAME}:${SAUCE_ACCESS_KEY}@ondemand.saucelabs.com:443/wd/hub
  sauceUserName: ${SAUCE_USERNAME}
  sauceAccessKey: ${SAUCE_ACCESS_KEY}
  deviceName: ${ANDROID_DEVICE_NAME}
  appFile: sauce-storage:${ANDROID_APP_FILENAME}
  platformVersion: ${ANDROID_PLATFORM_VERSION}
  idleTimeout: 630
  customCapabilities:
    isMock: true
    appiumVersion: 1.16.0
```

## Exception Stacktraces

https://gist.github.com/mrk-han/4654186b1cf4f2d16ee870019ccea1d7

https://github.com/appium/java-client/blob/6cd31e2b2eb979bea389918ac42f5b7ed6c40b60/src/main/java/io/appium/java_client/remote/AppiumCommandExecutor.java#L186

## Link To Appium Logs

N/A. because session is never created
